[package]
name = "pam_btbeacon"
version = "0.1.0"
edition = "2021"
authors = ["akosnad"]

[dependencies]
tokio = { version = "1.15", features = ["full"] }
futures = "0.3"
bluer = "0.13"
serde = { version = "1.0", features = ["derive"] }
serde_yaml = "0.8"
once_cell = "1.9"
